### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by forcazzx** [i2Nav-WHU/Wheel-INS#1]
How to run? Do you have cmakelists?

**Comment by YibinWu** [comment]
If you are a Windows user, just download the source code and create a project with the code in Visual Studio. Then you can compile and run it. Note that we use OpenCV to read the configuration file. If you a Linux user, download the source code and write your own CMakeList file to compile it and then run.  You may need to modify the code a little bit to adapt to the Linux enviroment.
