### ISSUE TITLE
ubuntu实现过程中undefined reference to....

### ISSUE THREAD

**Issue by fanfanfanfanzhou** [i2Nav-WHU/Wheel-INS#2]
`g++ cMatrix.cpp NavFunc.cpp main.cpp -o main
/usr/bin/ld: /tmp/ccsZa4uf.o: in function `main':
main.cpp:(.text+0x75): undefined reference to `cv::FileStorage::FileStorage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: main.cpp:(.text+0xae): undefined reference to `cv::FileStorage::isOpened() const'
/usr/bin/ld: main.cpp:(.text+0x112): undefined reference to `One_Sys_Main(cv::FileStorage)'
/usr/bin/ld: main.cpp:(.text+0x11e): undefined reference to `cv::FileStorage::~FileStorage()'
/usr/bin/ld: main.cpp:(.text+0x132): undefined reference to `cv::FileStorage::~FileStorage()'
/usr/bin/ld: main.cpp:(.text+0x1a1): undefined reference to `cv::FileStorage::~FileStorage()'
/usr/bin/ld: main.cpp:(.text+0x1b9): undefined reference to `cv::FileStorage::~FileStorage()'
/usr/bin/ld: /tmp/ccsZa4uf.o: in function `cv::FileStorage::FileStorage(cv::FileStorage const&)':
main.cpp:(.text._ZN2cv11FileStorageC2ERKS0_[_ZN2cv11FileStorageC5ERKS0_]+0x17): undefined reference to `vtable for cv::FileStorage'
collect2: error: ld returned 1 exit status`
我没有写cmaklist,而是直接手动编译g++ cMatrix.cpp NavFunc.cpp main.cpp -o main,但还是报错...尝试了很多方法依然不行.
希望可以得到你的帮助 @YibinWu

**Comment by fanfanfanfanzhou** [comment]
更新调试进展, 执行g++ cMatrix.cpp NavFunc.cpp main.cpp -o main `pkg-config opencv --cflags --libs opencv4后,目前就下面一个问题了:
`g++ cMatrix.cpp NavFunc.cpp main.cpp -o main `pkg-config opencv --cflags --libs opencv4`
/usr/bin/ld: /tmp/ccsfOlgV.o: in function `main':
main.cpp:(.text+0x112): undefined reference to `One_Sys_Main(cv::FileStorage)'
collect2: error: ld returned 1 exit status`

**Comment by YibinWu** [comment]
Hi, thanks for your interest in our study. A new version of the code supporting Ubuntu has been released! Please have a look!
