### ISSUE TITLE
代码报错

### ISSUE THREAD

**Issue by cao-3-stones** [i2Nav-WHU/Wheel-INS#3]
void getIMUparas(IMU_ConstPara * IMU, cv::FileStorage fs, cv::FileNode IMU_paras)
{
	cv::FileNodeIterator it1 = IMU_paras.begin();
	cv::FileNodeIterator it = ++IMU_paras.begin();
	**cv::FileNodeIterator it2 = --IMU_paras.end();**
	std::vector<double> leverarm, odo_std;
标粗的代码出现以下问题：一元“--”:“cv::FileNodeIterator”不定义该运算符或到预定义运算符可接收类型的转换
请问是否遇到过同样的问题，如果遇到过，是如何解决的。感谢。

**Comment by Octaneeeeee** [comment]
我也有同样的问题

**Comment by Octaneeeeee** [comment]
> void getIMUparas(IMU_ConstPara * IMU, cv::FileStorage fs, cv::FileNode IMU_paras) { cv::FileNodeIterator it1 = IMU_paras.begin(); cv::FileNodeIterator it = ++IMU_paras.begin(); **cv::FileNodeIterator it2 = --IMU_paras.end();** std::vector leverarm, odo_std; 标粗的代码出现以下问题：一元“--”:“cv::FileNodeIterator”不定义该运算符或到预定义运算符可接收类型的转换 请问是否遇到过同样的问题，如果遇到过，是如何解决的。感谢。

+1

**Comment by cao-3-stones** [comment]
是opencv版本的问题，使用低一点的版本，比如2.4.13

**Comment by Octaneeeeee** [comment]
> 

那对应的vs版本也要换么

**Comment by Octaneeeeee** [comment]
能加个QQ讨论一下么QQ：3295664342

**Comment by YibinWu** [comment]
Hi, the old code version is only tested with OpenCV 2413, so there would be an issue if you use other versions. However, a new version of the code without the requirement of OpenCV is now released. It supports both Windows and Ubuntu. Please have a look!
